server:  
  port: 8090
  contextPath: /pers
 
eureka:
  instance:
    hostname: ${vipAddress:ep-personalized-users}
    app: personalizedUsers
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${discovery.service.url}