server:  
  port: 8090
  
eureka:
  instance:
    hostname: ${vipAddress:ep-personalized-users}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${discovery.service.url}